#ifndef SOTP_NON_TRNG_CONFIG_MBEDOS
#define SOTP_NON_TRNG_CONFIG_MBEDOS

#define PAL_USE_HW_ROT 0
#define PAL_USE_HW_RTC 0
#define PAL_USE_HW_TRNG 0
#define PAL_SIMULATOR_FLASH_OVER_FILE_SYSTEM 0
#define PAL_USE_INTERNAL_FLASH 1
#define PAL_USE_SECURE_TIME 1

#define PAL_INT_FLASH_NUM_SECTIONS 2

#include "mbedOS_default.h"

#endif //SOTP_NON_TRNG_CONFIG_MBEDOS
