#ifndef PAL_HEADER_SOTP_FS_LINUX_LWM2M_COMPLIANT
#define PAL_HEADER_SOTP_FS_LINUX_LWM2M_COMPLIANT

#define PAL_USE_HW_ROT 0
#define PAL_USE_HW_RTC 0
#define PAL_USE_HW_TRNG 1
#define PAL_SIMULATOR_FLASH_OVER_FILE_SYSTEM 1
#define PAL_USE_SECURE_TIME 0

#include "Linux_default.h"

#endif //PAL_HEADER_SOTP_FS_LINUX_LWM2M_COMPLIANT
