#ifndef PAL_HEADER_SOTP_FS_ARIA_LINUX
#define PAL_HEADER_SOTP_FS_ARIA_LINUX

#define PAL_USE_HW_ROT 0
#define PAL_USE_HW_RTC 0
#define PAL_USE_HW_TRNG 1
#define PAL_SIMULATOR_FLASH_OVER_FILE_SYSTEM 1
#define PAL_USE_SECURE_TIME 1

#define PAL_TLS_CIPHER_SUITE PAL_TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256_SUITE

#include "Linux_default.h"

#endif //PAL_HEADER_SOTP_FS_ARIA_LINUX
