manifest:
  self:
    path: izuma-dm-example
  remotes:
    - name: PelionIoT
      url-base: https://github.com/PelionIoT
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: izuma-dm
      repo-path: mbed-cloud-client
      remote: PelionIoT
      revision: 571ac19a028abe553d11bcca58bca8e2f4d7c561
      path: modules/lib/izuma-dm
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      import: true
